# define Sheets (Tabs) to Read cells from as sections via [...]
#
# Example
# [Sheet 1]
# B9 = Title for Cells B9 in Sheets 1

[Freitag]
B9 = Anz Parkplätze
B10 = Anz Behindertenstellplätze
B11 = Anz Frauenstellplätze
B12 = Anz Familienstellplätze
B13 = Anz E-Stellplätze

[Für VGN]
C28 = Fr 6:00
D28 = Fr 7:00
E28 = Fr 8:00
F28 = Fr 9:00
G28 = Fr 10:00
H28 = Fr 11:00
I28 = Fr 12:00
J28 = Fr 13:00
K28 = Fr 14:00
L28 = Fr 15:00
M28 = Fr 16:00
N28 = Fr 17:00
O28 = Fr 18:00
P28 = Fr 19:00
Q28 = Fr 20:00